services:
  pipeline_chamber:
    build: .
    container_name: tcc_pipeline
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    env_file:          
      - .env           
    volumes:
      - ./data:/app/data
      - ./src:/app/src

  tests:
    build: .
    container_name: tcc_tests
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./data:/app/data 
      - ./src:/app/src
    command: pytest src/tests/ -v --cov=src